export const LOAD_REPOS_REQUEST = 'LOAD_REPOS_REQUEST';
export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_FAIL = 'LOAD_REPOS_FAIL';
export const UPDATE_REPOS = 'UPDATE_REPOS';